# Site settings
title: sol blog
# email: your-email@example.com
description: ""
baseurl: ""
github_username: sol-e-e

# Build settings
remote_theme: chesterhow/tale
markdown: kramdown
include:
  - _pages

# Permalinks
permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed
