# Site settings
title: sol blog
# email: your-email@example.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sol-e-e.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sol-e-e

# Build settings
# theme: minima
remote_theme: chesterhow/tale
markdown:       kramdown
include:
  - _pages

# Permalinks
permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
